### ISSUE TITLE
LaTeX support?

### ISSUE THREAD

**Issue by NicusorN5** [GraphicsProgramming/learnd3d11#32]
Hi,

This is more like a "feature request" instead of a "issue": (I think creating a discussion thread is a better choice)

I was thinking about starting to write the articles about linear transformations and coordinate systems. I'd like using LaTeX since it is TON easier for me to write mathematical formulas and articles with it. Is this possible? 

I might try using Markdown, but I'm not sure if stuff is going to look as good as in latex. I'm also not really familiar with it.

Thanks.

**Comment by deccer** [comment]
We are using markdown. It's a well established way of writing these kind of "documents". We are not writing a thesis or phd paper where LaTex seems to be the norm.

**Comment by spnda** [comment]
However, it might be beneficial to have some kind of math rendering going, especially in the PBR and lighting chapters, where a lot of the content is simply maths. I'm not sure about the options we have in MD though, but it might still be something to think about in the long run.

**Comment by NicusorN5** [comment]
I will try to setup LaTeX rendering on MkDocs on a separate branch of mine, Will create a PR if finished.

**Comment by Alyx6020** [comment]
![formula](https://render.githubusercontent.com/render/math?math=\color{white}\large\f(x)=sin(x))
found from [https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b](url)

**Comment by NicusorN5** [comment]
Btw that link is broken, I had to copy the address into the browser lol
