### ISSUE TITLE
Come up with a structure for the first section of the tutorial series to get a rough idea what we need to add/implement/copy

### ISSUE THREAD

**Issue by deccer** [GraphicsProgramming/learnd3d11#37]
# Introduction

# Getting Started

  - What D3D11 and GPU APIs actually do
  - Cram a picture in here of the DX11 graphics pipeline to show where we are, and what we need
  - GLFW window (HelloWindow) with link to HelloWin32Window (but no going through what it all means)
  - D3D11 initialization, Raw Pointers vs ComPtr (HelloComApplication) and (HelloD3D11)
  - Swapchain creation, clearing and resizing the screen
  - Hello Triangle
    - Shaders
      - Show how they can be compiled with VS?
      - Explain how to compile from code (D3D11CompileFromFile...)
    - InputLayout
    - VertexBuffer
    - Explain vertex/indexbuffers, primitivetopology, shaders (overview) and RasterizerStates\

# Debug and how to help yourself

  - ClearState and explain why this is useful
  - Debug Layer/Debug Device
  - Naming things
  - RenderDoc
  - NvOptimusEnablement/AmdWhateverPerformance for laptop users

# Model Loading

  - Loading Textures (HelloFroge) (that means introducing an image library)
  - Loading Meshes
  - Loading Materials/Textures
  - DepthStencilTexture+DSV
  - DepthStencilState
  - IndexBuffer
  - Math
    - Coordinate Systems
    - Shader support for -> (Would be cool if we we could apply terminology to shaders too and have easy ways of conversion between those... @neure is using something like that in their engine... clipToWorld, clipToView, worldToView etc imoh that makes things easier to grasp
  - Constant Buffers
  - A camera to admire froge
 
 ~~Does it make sense to come up with some sort of "Scene" VkGuide also mentions that and it makes sense imho (this could lead to advanced articles to either how to use ecs like entt, or whatever)~~

**Comment by deccer** [comment]
# Introduction

# Getting Started

  - What D3D11 and GPU APIs actually do
  - Win32 window and then GLFW window
  - COM and D3D11 initialization
  - Swapchain creation and clearing the screen
  - Hello triangle
  - Shaders
  - Textures and Froge
  - Math behind transforms and etc
  - A camera to admire froge

# Model Loading

  - Building/Downloading Assimp
  - Loading Meshes
  - Loading Materials/Textures

# Basic Lighting

  - Colors
  - Blinn-Phong with hardcoded directional light
  - Blinn-Phong materials and lights
  - Point and directional lights from the CPU
  - Gamma Correction
  - Normal Mapping
  - Shadows
  - Deferred Shading

# PBR

  - Rendering equation and basic theory
  - Used BRDFs
  - Physically based lighting
  - IBL with SH

# Techniques

  - Text Rendering
  - Particles
  - Skeletal Animation
  - CSM
  - SSAO
  - SSR
  - Frustum Culling
  - Sky + Clouds
  - Reflection probes

# Post-processing

  - HDR + Tonemapping
  - Better camera + Bloom
  - Depth of Field
  - TAA
  - Motion Blur
  - Lens flare

**Comment by Diamond-D0gs** [comment]
I feel the GI section under Techniques might be a bit out of scope for a beginner.

**Comment by deccer** [comment]
> I feel the GI section under Techniques might be a bit out of scope for a beginner.

Where should it go into? I understand Techniques as some sort of mix between "Advanced Topics" and "Stuff modern engines do anywa"

**Comment by Diamond-D0gs** [comment]
> > I feel the GI section under Techniques might be a bit out of scope for a beginner.
> 
> Where should it go into? I understand Techniques as some sort of mix between "Advanced Topics" and "Stuff modern engines do anyway". And this is not only sold as a 100% noob thing and then you stop after the projected textures section... Ah Texture Projection could be another section 👯

Idk, just feels out of scope for this tutorial as a whole. I feel they can go learn and implement Voxel GI themselves if they feel so inclined.

**Comment by deccer** [comment]
> > > I feel the GI section under Techniques might be a bit out of scope for a beginner.
> > 
> > 
> > Where should it go into? I understand Techniques as some sort of mix between "Advanced Topics" and "Stuff modern engines do anyway". And this is not only sold as a 100% noob thing and then you stop after the projected textures section... Ah Texture Projection could be another section 👯
> 
> Idk, just feels out of scope for this tutorial as a whole. I feel they can go learn and implement Voxel GI themselves if they feel so inclined.

Isnt that true for other topics as well then?

**Comment by Diamond-D0gs** [comment]
Maybe we have 2 different views of what this tutorial series is. I view this as a way for a burgeoning GP to get their legs to help them research and implement more advanced techniques, learn a more advanced API, etc.

**Comment by deccer** [comment]
Yes, it will be. We wont be adding GI that quick anyway, it just crossed my mind.

And would it hurt? That's exactly what LOGL lacks, there's only a few odd guest articles in there, which are in a complete different format than Joeys'. 

To have one resource for all the things you would want to implement using d3d11 could very well be the thing we are working on right now. One step at a time.

**Comment by deccer** [comment]
Yes, it will be. We wont be adding GI that quick anyway, it just crossed my mind.

And would it hurt? That's exactly what LOGL lacks, there's only a few odd guest articles in there, which are in a complete different format than Joeys'. 

To have one resource for all the things you would want to implement using d3d11 could very well be the thing we are working on right now. One step at a time.

**Comment by nickclark2016** [comment]
> I feel the GI section under Techniques might be a bit out of scope for a beginner.

Just call it intermediate?

**Comment by deccer** [comment]
I think `Techniques` could have a little tag of some kind, to indicate whether this is a complex, simple, or something in between (although that depends on how well you understand every topic i guess)

**Comment by Diamond-D0gs** [comment]
Why is Forward+ under Deferred Rendering? Also we should reorder that section so Forward+ rendering is completed before Deferred Rendering so the clustered lighting system can be used for rendering opaque objects with Deferred and they'll have the Forward+ renderer to use for transparent objects/

**Comment by deccer** [comment]
The order was chosen arbitrarily. Let me adjust that

**Comment by Diamond-D0gs** [comment]
I'd also swap Classical Deferred and Tightly Packed G-buffer, establish the theory first and then present how it's typically done in practice.

**Comment by deccer** [comment]
We extensively discussed during VC and that was the outcome for part 1.

Once we have that going, explaining everything + providing source etc, we want to have people try it out, to get feedback and then go from there
