### ISSUE TITLE
1-1-0: Diagram of D3D11 Pipeline/stages + explanation

### ISSUE THREAD

**Issue by deccer** [GraphicsProgramming/learnd3d11#43]
Construct a [Mermaid](https://mermaid-js.github.io/mermaid/#/stateDiagram) diagram to show the various pipelines/stages

**Comment by deccer** [comment]
Not sure, mermaid looks like ass for some reason. maybe we should look into some alternative thing.. i wonder if `graphviz` has something nice.


![image](https://user-images.githubusercontent.com/15695435/157122847-7838fcca-a7fb-42a1-ac42-b4146331295b.png)

**Comment by AlexB8675** [comment]
I haven't looked into graphviz but I think the mermain graph looks fine, what's the problem with it?

**Comment by deccer** [comment]
Its "supposed" to resemble something like this

![image](https://user-images.githubusercontent.com/15695435/157125675-0b31d754-03c2-4ea2-a0cb-9bbcaeab94c8.png)

**Comment by deccer** [comment]
This has been implemented already
