### ISSUE TITLE
Nuke wstring where possible, convert at location from string instead

### ISSUE THREAD

**Issue by Themperror** [GraphicsProgramming/learnd3d11#74]
it's a hassle keeping a mix of string and wstring in things, you'll keep running into situations where you have your string variable but it wants a wstring or vice versa later. keeping one of the two and converting seems way more convenient (and vouch for string for utf8)

example conversion utility:

    std::wstring ToWideString(const std::string& string)
    {
        std::wstring newString(string.size()*sizeof(wchar_t), '\0');
        size_t numCharsConverted = 0;
        mbstowcs_s(&numCharsConverted, newString.data(), newString.size(), string.data(), string.size());
        newString.resize(numCharsConverted-1);
        return newString;
    }

**Comment by Themperror** [comment]
Added remark to remove string_view when we pass them into API's taking const char* or stuff like that (since string_view does not require null-terminators)

**Comment by AlexB8675** [comment]
I would be leaning torwards `const std::wstring&` rather than `const wchar_t*`

**Comment by Themperror** [comment]
> I would be leaning torwards `const std::wstring&` rather than `const wchar_t*`, but either way is fine

I meant it in contexts where we need to pass a string into an external API that takes a C string, where we need to make sure said string contains a null-terminator
