### ISSUE TITLE
Projects: Move Viewport/SetViewport

### ISSUE THREAD

**Issue by deccer** [GraphicsProgramming/learnd3d11#86]
At the moment `DeviceContext` has SetViewport, that should be moved to ~~`PipelineSettings`~~ `Pipeline`

**Comment by AlexB8675** [comment]
Did you mean `Pipeline`?

**Comment by deccer** [comment]
Hmm I was thinking viewport is defined during creation time, or is that one of those dynamic things like samplers/resources?

**Comment by AlexB8675** [comment]
Well, technically the viewport is defined at creation time (at least in Vulkan) but I pretty much always set that as a dynamic state, since we want the window to be resizable we should make the Viewport a dynamic state too.

**Comment by deccer** [comment]
Good point, I forgor about resizing, will update the descrptiorn

**Comment by deccer** [comment]
Fixed
