### ISSUE TITLE
1-1-3-HelloD3D11: Explain INPUT_ELEMENT_DESC better

### ISSUE THREAD

**Issue by deccer** [GraphicsProgramming/learnd3d11#95]
Jkr suggests that the elements should be explained in more detail

**Comment by 16-Bit-Dog** [comment]
I'll hop on doing this issue next

**Comment by 16-Bit-Dog** [comment]
turns out issue is the wrong name- so prior work is irrelevant and this issue will be renamed

**Comment by 16-Bit-Dog** [comment]
#126 (tagging)

**Comment by deccer** [comment]
fixed with !126
